name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # taiki-e/create-gh-release-action@v1.11.0
      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651
        with:
          changelog: CHANGELOG.md

  upload-assets:
    name: Upload ${{ matrix.target }}
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            build_tool: cargo
          - target: aarch64-apple-darwin
            os: macos-latest
            build_tool: cargo
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            build_tool: cargo
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cross
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            build_tool: cross
    steps:
      - uses: actions/checkout@v4
      # taiki-e/upload-rust-binary-action@v1.30.2
      - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6
        with:
          bin: envlens
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build_tool }}
          tar: unix
          checksum: sha256
